# Generated by Django 2.1.7 on 2019-03-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('accessoriesId', models.IntegerField(primary_key=True, serialize=False)),
                ('accessoriesName', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='product', verbose_name='Accessories_Image')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoriesId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoriesName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('computerId', models.IntegerField(primary_key=True, serialize=False)),
                ('computerName', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300, null=True)),
                ('processor', models.CharField(max_length=300, null=True)),
                ('operating', models.CharField(max_length=300, null=True, verbose_name='Operating_System')),
                ('memory', models.CharField(max_length=300, null=True)),
                ('hardDrive', models.CharField(max_length=300, null=True)),
                ('display', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='product', verbose_name='Product_Image')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Custome_ID')),
                ('customerName', models.CharField(max_length=30, verbose_name='Custome_Name')),
                ('customerEmail', models.CharField(max_length=30, verbose_name='Custome_Email')),
                ('password', models.CharField(max_length=30)),
                ('billAddr', models.CharField(max_length=150, null=True, verbose_name='Billing_Address')),
                ('shipAddr', models.CharField(max_length=150, null=True, verbose_name='Shipping_Address')),
                ('Contact', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('customizeId', models.IntegerField(primary_key=True, serialize=False)),
                ('customizeName', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='product', verbose_name='Customize_Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2z.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('billAddr', models.CharField(max_length=150, null=True, verbose_name='Billing_Address')),
                ('shipAddr', models.CharField(max_length=150, null=True, verbose_name='Shipping_Address')),
                ('amount', models.IntegerField()),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2z.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2z.Computer')),
                ('orderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2z.Order')),
            ],
        ),
    ]
