# Generated by Django 2.1.7 on 2019-03-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2z', '0003_auto_20190316_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerEmail',
            field=models.EmailField(max_length=128, unique=True, verbose_name='Customer_Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerName',
            field=models.CharField(max_length=128, unique=True, verbose_name='Customer_Name'),
        ),
    ]
