# Generated by Django 2.1.7 on 2019-03-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a2z', '0004_auto_20190318_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('userEmail', models.EmailField(max_length=128, unique=True, verbose_name='Customer_Email')),
                ('billAddr', models.CharField(max_length=150, null=True, verbose_name='Billing_Address')),
                ('shipAddr', models.CharField(max_length=150, null=True, verbose_name='Shipping_Address')),
                ('contact', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2z.User'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
